package com.example.yesnightmarket.tool.http

enum class SQLTYPE (val SQL_TYPE: String){
    PRIMARY_KEY("INT PRIMARY KEY AUTO_INCREMENT"),
    INT("INT NOT NULL"),
    STRING_PRIMARY_KEY("VARCHAR(255) PRIMARY KEY NOT NULL"),
    STRING("VARCHAR(255) NOT NULL"),
    TEXT("TEXT NOT NULL"),
    BOOLEAN("BOOLEAN NOT NULL"),
    DATE("DATE NOT NULL"),
    TIMESTAMP("TIMESTAMP DEFAULT CURRENT_TIMESTAMP"),
    FLOAT("FLOAT NOT NULL"),
    DOUBLE("DOUBLE NOT NULL"),
    BIGINT("BIGINT NOT NULL"),
    SMALLINT("SMALLINT NOT NULL")
}
